### ISSUE TITLE
Avoid multi-fold computation times when computing ancillary features that rely on same pipeline.

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#104]
Some features (e.g. [bright_avg](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/rtdc_dataset/ancillaries/af_image_contour.py#L11) and [bright_sd](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/rtdc_dataset/ancillaries/af_image_contour.py#L19)) rely on the same function. This is inefficient, since the function is called twice for each event. There are more and more ancillary features (think of Haralick texture features) that are derived using one method. It would be good to have an option for ancillary features to define other ancillary features.

It should be implemented transparently without breaking any current ancillary features if possible.

**Comment by PinkShnack** [comment]
To take the `bright_*` example, the `features.bright.get_bright` function only deviates between `svg` and `avg` on line 62:
```python
if ret_avg:
    avg[ii] = np.mean(imgi[mski])
if ret_std:
    std[ii] = np.std(imgi[mski])
```
Do you mean that there should be a function that calculates the input to the `np.mean` and `np.std` and caches the result, so that it doesn't have to be rerun again for the same event? In this case the time saves would be very small, right?

Is the aim here to break down these functions to their smallest part to give us more building blocks for other `AncillaryFeatures`? Could you give another few examples please? Then I might be able to wrap my head around it.

**Comment by paulmueller** [comment]
Yeah, I see. The `bright_*` example is not a really good one. The only overhead is the cell event image extraction using the mask, which is done twice currently.

A more extreme example: Let's say all contour moments defined in https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/inert_ratio.py#L7 should become ancillary features (e.g. "mu20", "mu11", "mu02"). The current way `AncillaryFeature` is implemented does not allow to just compute all moments for one event and then set the corresponding feature. Ideally, if the user wants to access "mu20", then "mu11" and "mu02" are also populated automatically.

My initial idea of an implementation would be to pass an argument to AncillaryFeature called `computes_also=["mu20","mu11", ..]` and then internally it does some magic to do the feature population...
