### ISSUE TITLE
new, faster histogram approach to determine kernel density

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#2]
@MaikH88 you were experimenting with a histogram-based kernel density estimator. Could you please send me an example code so I can implement it in dclab/ShapeOut?

**Comment by MaikH88** [comment]
I think it would be best if the standard setting just draws all points 'black' instead of using any density estimator. Most users filter out a lot of data before they are actually are interested to get the density.
Please find some source code attached:

[MixtureModels_1.txt](https://github.com/ZellMechanik-Dresden/dclab/files/265136/MixtureModels_1.txt)

**Comment by paulmueller** [comment]
Hmm, I have the feeling that scikit-learn will unnecessarily blow up ShapeOut. Is this approach really faster than the KDEs we currently have? I was hoping you already found a faster/more inaccurate (based on histograms) way to compute kernel densities.

**Comment by paulmueller** [comment]
This might be useful: https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.histogram2d.html
