### ISSUE TITLE
Improve data visualization for log-scale

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#55]
The original problem was raised by @maikherbig in https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/pull/230.

When the user wants to plot log-data, then the KDE is still computed on a linear scale and looks unintuitive. This also affects downsampling.

TODO: Add ``scale`` argument to

- [x] ``RTDCBase.get_downsampled_scatter``
- [x] ``RTDCBase.get_kde_contour`` ~(???)~
- [x] ``RTDCBase.get_kde_scatter``

**Comment by paulmueller** [comment]
Note: Some features might exhibit negative values. How do we deal with that?

**Comment by maikherbig** [comment]
Which features could potentially be negative? So far I only saw FL_max and FL_area features being negative, but this is actually not a sensible value since the detectors cannot detect a negative amount of photons. Negative fluorescence values are therefore noise and I would suggest:
ind = np.where(fl<1)[0]
fl[ind] = 1
Beside negative values, even zero values are not defined for log-transformations, which can appear for: flx_area, (flx_max), flx_width, flx_dist, flx_npeaks ,flx_pos,tilt and time. This could be circumvented using:
ind = np.where(x<=0)[0]
x[ind] = np.nan
, but a warning message should be thrown, indicating how many events are not shown due to the scaling issue. 
Scaling should also be performed before computing the contour.

Maybe one more issue that is probably related: If one has a measurement with negative flmax values and one plots this using scale=log, then some scatter points at flx_max=0 are invisible:
![plotting_issue](https://user-images.githubusercontent.com/14074051/48289999-a70ec300-e471-11e8-8ba4-352ad2e407ae.png)

**Comment by paulmueller** [comment]
I have added the `xscale` and `yscale` arguements (see commit above).

As you said, negative / nan / inf values are not a problem. They are handled well by all relevant methods anyway.

TODO:
- [ ] test for `get_kde_scatter`
- [ ] test for `get_kde_contour`
- [ ] A new problem in ShapeOut is the "accuracy" setting, which would have to be automatically adapted when the user chooses the log scale. How should this be done?

**Comment by chrherold** [comment]
Just a quick remark 

> FL_max and FL_area features being negative, but this is actually not a sensible value since the detectors cannot detect a negative amount of photons. Negative fluorescence values are therefore noise and I would suggest...

This is only true if raw data is not altered by operations like fluorescence compensation. After compensation negative values of FL_max are very much expected and compensation would not work correctly if they are not there. 

So actually we might want to think about some pseudo-log representation that allows to display negative values.

**Comment by paulmueller** [comment]
@chrherold A pseudo-log scale involves several things that would have to be implemented in both, dclab and ShapeOut. I also have the feeling that there are a lot of pitfalls. I have created a new issue, so we can address this another time: #56
