### ISSUE TITLE
calling dataset['contour'] very slow

### ISSUE THREAD

**Issue by felix-r** [ZELLMECHANIK-DRESDEN/dclab#61]
I currently work on a big dataset and figured that calling objects from `dclab.dataset['contour']` slows down the script immensely. This is also the case for smaller datasets, just not that obvious. I call the contours from a hierachy_child of a filtered dataset the following:

    in_file = r"\\biotec-files\guck_rtdc\experiments_18_19\20190523_Felix_WBCs_longchannel\MC0.6_Dexfractionated_2\M002_data.rtdc"
    ds = dclab.new_dataset(in_file)
    first_frame = 0    
    last_frame = 1000  
    ds.config["filtering"]["frame min"] = ds['frame'][first_frame] 
    ds.config["filtering"]["frame max"] = ds['frame'][last_frame]
    ds.apply_filter()  # this step is important!
    
    ds_filtered = dclab.new_dataset(ds)
    #e.g.: 
    cnt = ds_filtered['contour'][0]

If I try to call the contour in a IPython console I found that it only takes so long when I call the contour feature for the first time. After that any operation works reasonably fast: 

![image](https://user-images.githubusercontent.com/19806005/58558936-5058b300-8222-11e9-9c11-4ce189617872.png)

I do not observe this behavior for other non-scalar features like `'image'` and don't really understand why it should by any different for `contour`. An improvement would be highly appreciated.

Specs:
python: 3.6.3
dclab v0.10.5
OS: Windows 10

**Comment by felix-r** [comment]
Ok I just realized that the contour has to be computed first because it is not included in the measurement file. But why? The contour is already computed during the measurement to display the deformation of each cell. Before you introduced the .rtdc format the contours were saved in a seperate file. Would it be feasible to include the contours in the .rtdc file directly from the measurement or what is the reason we compute it again offline?

**Comment by paulmueller** [comment]
In short, there is a difference between "contour" and "mask". "mask" is stored in the rtdc file. As far as I know, storing contour data was not fast enough for real-time applications, because it does not have a fixed size (contours can be long or short), which made storing it in an hdf5 file slow, right @phidahl ? For this reason, contours are computed offline.

Do you need this to be faster?

**Comment by felix-r** [comment]
I guess it would already help if the contours only get computed for the filtered dataset/hierachy child. In my example I only need the contours after filtering. But the time to get the contours still depends on the total size of the initial dataset. So, I assume the contours are computed for the parent dataset as well. Could this be changed or is this not how operations on child- and parent sets are intended?

Besides, I found out how to export datasets (using dclab, of course!) with the contours or other features that need offline computation first (e.g. volume, elastic modulus ...). Operation on these files is reasonably fast again and a feasible workaround for now.

**Comment by phidahl** [comment]
Yes, @paulmueller saving the contour vectors with non-predetermined length was less efficient than saving a binary image. Also the file format is less complicated this way. It is not planned to change the .rtdc file format regarding this.
I think that we could either change behavior of dclab to compute only the contours which are actually needed, or you could perform a cv2.findContours on the binary images of interest, giving you the contours you need.

**Comment by paulmueller** [comment]
@felix-r In dclab 0.11.0, contours will be computed lazily. This means that not all contours will be computed when you only need them for a hierarchy child. If you really need this to be fast, you could make use of `cv2.findContours` on the `"mask"` data (as suggested by @phidahl), which should give you the same result (for events that make sense physically).

Note: The implementation in dclab is slow, because it actually takes a detour. There already is some effort in the scikit-image community to make it faster: https://github.com/scikit-image/scikit-image/issues/1131. Another option would be to port the OpenCV implementation to Cython so that we can use it in dclab. However, this is outside of the scope of this issue.

**Comment by felix-r** [comment]
Alright, this sounds like a good solution. I might use the `cv2.findContours`  workaround if I need it faster. Thanks!
