### ISSUE TITLE
contours: binary erosion (plotting only) vs. scikit image (orientation)

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#76]
In Shape-Out 2, we are using

```python
cont = mask ^ binary_erosion(mask)
```
to obtain the contour image.

Is this identical to what we get if we map the contour from `dclab.features.contour.get_contour` onto a grid?

**Comment by paulmueller** [comment]
For the sake of having good-first-issues, I am making this one here a good first issue as well.

This will likely not converge to a PR, but it involves image analysis tasks and I hope it will yield some closure regarding contour extraction from mask images.

What you will learn:
- Getting to know ancillary features in dclab.

Explanation of the issue:
- Back in the days of .tdms measurements, the [`contour` feature](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/definitions.py#L235) was stored alongside the .tdms file in a separate text file. The contour feature is a list of x-y-coordinates [px] that trace the circular contour.
- Shape-In 2 does not anymore store the contour feature, because the dataset lengths are not fixed which makes it inconvenient for real-time writing. Shape-In 2 stores the "mask" images instead.
- dclab has an ancillary feature to compute contours from mask images: https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/contour.py (which is overkill / not very efficient, but this is not the point here)
- Shape-Out 2 also shows the contour in the QuickView window, but it computes the contour with `cont = mask ^ binary_erosion(mask)` and **not** with `dclab.features.contour.get_contour`, because Shape-Out 2 just plots the contour - the order of the circular contour points is irrelevant.
- The question now is: Are 2D contour image from `cont = mask ^ binary_erosion(mask)` and `dclab.features.contour.get_contour` identical?

Task:
- Compute the contour images for several representative RT-DC datasets (e.g. blood measurements and beads) using both of the methods mentioned above. You can e.g. download datasets from DCOR [[1](https://dcor.mpl.mpg.de/dataset/figshare-11662773-v2), [2](https://dcor.mpl.mpg.de/dataset/figshare-11302595-v1)]
- Are the contour images the same? Are there only weird special cases where the contours don't match up, or did I screw up when I introduced `cont = mask ^ binary_erosion(mask)` in Shape-Out 2?

**Comment by PinkShnack** [comment]
I shall find out if you "screw[ed] up when I introduced cont = `mask ^ binary_erosion(mask)` in Shape-Out 2"!

**Comment by paulmueller** [comment]
Thank you!

**Comment by PinkShnack** [comment]
Short review of what I've found so far here.

I checked if the contour coordinates are the same between the XOR (`^`) method and the `skimage` method. Damn that XOR method is slick.
There are differences between the two methods, summarised below. Let me know if these datasets should have any issues like this...

It seems like both methods output duplicates. This I expect from the XOR method, but not from the `skimage `method

**Data001**: Arrays do not match in 10.273% of cases (9.677% after duplicate removal)
**Data002**: Arrays do not match in 6.863% of cases (6.418% after duplicate removal)
**Data003**: Arrays do not match in 7.418% of cases (6.987% after duplicate removal)

### To do:
- I think I should look at how much of a difference there is between the method outputs.
- I will do a speed test between the methods.

**Comment by paulmueller** [comment]
What exactly is a duplicate? A contour should not have the same point twice (unless it's a closed contour?). I would not expect that from the XOR method. Anyway, thanks for looking into this.

Please also check whether this affects the [inertia ratio](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/inert_ratio.py) and [volume](https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/features/volume.py) ancillary features. Maybe the differences in the contours are small enough to be insignificant...

**Comment by PinkShnack** [comment]
My sorting method was screwing with the arrays and adding duplicates. Since fixed.

It seems that all of the contour positions (xy points in contour array) of the XOR method are accounted for in the skimage contours, which one would expect. In other words, there are no positions in the XOR method that are not in the skimage method.

The skimage contours sometimes contain "duplicates". By this I mean that the first point of the contour is also the last; a closed contour as you mentioned. For cell events that are badly contoured (see attached image), this can mean many duplicates as it draws the contour over the same spot several times (12 in the attached image's cases). 

I will have a look at the `inertia ratio` and `volume `as you suggested.

It would seem that the XOR method is suitable for plotting the data as it does not have duplicates, is probably faster, and if you use alpha transparency you won't get strange shading (as I used to show the duplicates in the attached image). However it is not exactly the same as the skimage contour method every time.

The extra big red points are exaggerated to highlight where the duplicates are.

![XOR_skimage_contouring](https://user-images.githubusercontent.com/43960046/109329092-788f9e80-785a-11eb-8e84-f55b3c3c2c11.png)

**Comment by paulmueller** [comment]
Ah, now I get it. Thanks for the clarification. Also feels good to know that the mapped contours are identical. A general remark: contours that show those duplicates, especially the example you show here, are usually filtered out via porosity (`area_ratio`), as they are not "physical".

**Comment by PinkShnack** [comment]
Regarding `volume` and `inert_ratio`. 
After discussion with Paul, both need the contour to be counterclockwise (or clockwise) for consistent results. 

As I had already checked their behaviour out, I thought it'd be good to sumarise below so we have them at a glance.

### volume
`get_volume `
- **not consistent** between two very similar contours of equal length
- **not consistent** between skimage contour and XOR contour

### inert_ratio
`get_inert_ratio_cvx `- **Good**  - consistent between XOR method and skimage method.
`get_inert_ratio_prnc` - Does not work for XOR contour - probably due to the lack of counter-clockwise-ness/contour order.
`get_inert_ratio_raw` - Depends on counterclockwise-ness (not consistent between similar arrays)
