### ISSUE TITLE
readthedocs does not show correct docstrings (autodoc)

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/dclab#94]
There is an issue with the docs displayed on readthedocs.io and the doc strings of constants (and potentially other doc strings as well).

E.g. the doc string for CFG_ANALYSIS should read

https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/21c0fdf29daca41d6efeeffdfd976d4aa88ad3e7/dclab/definitions.py#L8-L9

...but on RTD it is "User-editable configuration for data analysis.", which is from some older commit I think.

https://dclab.readthedocs.io/en/stable/sec_code_reference.html#dclab.dfn.CFG_ANALYSIS

My guess is that readthedocs/autodoc somehow caches data from previous runs.

What you will learn:
- familiarize yourself with https://docs.readthedocs.io

Notes:
- RTD does not run on pull requests. But I think I could set that up once you created one - just let me know if you would like to work on this.

**Comment by maxschloegel** [comment]
I was trying to solve the issue. There were two main layers to it:
1. As discussed with @paulmueller, the documentation on RTD was still hardcoded into the '*.rst'-files.
2. After removing them, I changed

`.. data:: dclab.dfn.CFG_ANALYSIS

    User-editable configuration for data analysis.`
to
`.. autodata:: dclab.dfn.CFG_ANALYSIS
   :no-value:`.

Unfortunately there seems to be a bug, where `..autodata::` does not include the docstring, when `dfn` is used instead of `definitions`, while `dfn` works fine for `.. autofunction::` (as is `.. autofunction:: dclab.dfn.feature_exists`)

I will go through the rest of `*.rst`-files and look for other such cases and change them accordingly.

**Comment by maxschloegel** [comment]
Two more smaller points:
The above mentioned need to change `dfn` to `definitions` for the module variables will introduce inconsistency between module variables and module functions in RTD. 
Additionally when comparing the differences of using `definitions` instead of `dfn` for `..autofunction::` we see that only the version with `definitions` includes a link to the source code. Since this is the case for any other functions (no other module is imported under a different name than `definitions`), this is also a (very tiny) inconsistency:

![image](https://user-images.githubusercontent.com/30384152/109660460-2f489300-7b69-11eb-98d6-85dd571155ed.png)

Should I also change the reference to the functions from `dfn` to `definitions` ?

**Comment by paulmueller** [comment]
Yes, I think it would be best to then just stick to `definitions`. I guess we could keep the import of `definitions as dfn` in `__init__.py` for user convenience, but not officially document it. Thanks for the insight!

**Comment by maxschloegel** [comment]
Ok, thanks!
